name: deeznote
version: 0.1.0
publish_to: none
description: A notulensi app for PT. Des Teknologi Informasi
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  currency_formatter: ^2.0.1
  draggable_bottom_sheet: ^1.0.2
  flutter_screenutil: ^5.9.0
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: any
  liquid_pull_to_refresh: ^3.0.1
  photo_view: ^0.14.0
  dio: ^5.3.3
  retrofit: any
  shimmer: ^3.0.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  overlay_support: ^2.1.0
  flutter_animate: ^4.3.0
  syncfusion_flutter_datepicker: ^24.2.7
  change_app_package_name: ^1.1.0
  http_parser: ^4.0.2
  socket_io_client: ^2.0.3+1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.2
  table_calendar: ^3.0.9
  animations: ^2.0.11
  animate_do: ^3.3.3
  syncfusion_flutter_signaturepad: ^24.2.8
  html_editor_enhanced: ^2.5.1
  get: 4.6.6
  flutter:
    sdk: flutter
  simple_circular_progress_bar: ^1.0.2
  file_picker: ^5.5.0

dev_dependencies:
  build_runner: any
  built_value_generator: any
  flutter_lints: ^2.0.0
  json_serializable: any
  retrofit_generator: any
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
